### ISSUE TITLE
tensorflow 2.0

### ISSUE THREAD

**Issue by happiness-ai** [titu1994/keras-LAMB-Optimizer#1]
tensorflow2.0

Traceback (most recent call last):
  File "F:/workspace/python/tf-fit/keras_plus/optimizer/test.py", line 26, in <module>
    model.fit(x_train, y, epochs=5)
  File "E:\Anaconda3_5_0_0\envs\DeepLearning\lib\site-packages\tensorflow\python\keras\engine\training.py", line 873, in fit
    steps_name='steps_per_epoch')
  File "E:\Anaconda3_5_0_0\envs\DeepLearning\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 151, in model_iteration
    f = _make_execution_function(model, mode)
  File "E:\Anaconda3_5_0_0\envs\DeepLearning\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 521, in _make_execution_function
    return model._make_execution_function(mode)
  File "E:\Anaconda3_5_0_0\envs\DeepLearning\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2231, in _make_execution_function
    self._make_fit_function()
  File "E:\Anaconda3_5_0_0\envs\DeepLearning\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2177, in _make_fit_function
    '_fit_function', [self.total_loss] + metrics_tensors)
  File "E:\Anaconda3_5_0_0\envs\DeepLearning\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2149, in _make_train_function_helper
    params=self._collected_trainable_weights, loss=self.total_loss)
  File "F:\workspace\python\tf-fit\keras_plus\optimizer\lamb.py", line 65, in get_updates
    self.weights = [self.iterations] + ms + vs
  File "E:\Anaconda3_5_0_0\envs\DeepLearning\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py", line 507, in __setattr__
    super(OptimizerV2, self).__setattr__(name, value)
AttributeError: can't set attribute

**Comment by titu1994** [comment]
Keras 2.2.4 does not yet support Tensorflow 2.0.
